### ISSUE TITLE
bug: validate require CLI config when using TFC "remote" backend

### ISSUE THREAD

**Issue by sandangel** [hashicorp/terraform-github-actions#102]
Hi, I would like to report a bug. The `validate` subcommand does require TF CLI config .terraformrc. This is my workaround by overriding the docker entry point but it would be nice if TF GitHub actions could handle it.

```yaml
name: Terraform
on: [pull_request]

jobs:
  linting:
    name: Terraform - Linting
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dirs: [cloudflare, network, iam, shared, live/qa1, live/stg, live/front-proxy]
    steps:
      - uses: actions/checkout@master

      - name: Terraform - Format
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_version: 0.12.13
          tf_actions_subcommand: fmt
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Terraform - Init
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_version: 0.12.13
          tf_actions_subcommand: init
          tf_actions_working_dir: ${{ matrix.dirs }}
        env:
          TF_CLI_ARGS_init: '-backend-config token=${{ secrets.TFE_TOKEN }}'

      - name: Terraform - Validate
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_version: 0.12.13
          tf_actions_subcommand: validate
          tf_actions_working_dir: ${{ matrix.dirs }}
          entrypoint: sh
          args: -c "echo credentials app.terraform.io { token = \\\"${TFE_TOKEN}\\\" } > ~/.terraformrc; /src/main.sh"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TFE_TOKEN: ${{ secrets.TFE_TOKEN }}
```

I tried with both `TF_CLI_ARGS_init: -backend-config token=${{ secrets.TFE_TOKEN }}` then `-backend=false` at the Init step, but they all failed with this error if I don't override the docker entry point:

```sh
Error: Required token could not be found

Make sure you configured a credentials block for app.terraform.io in your CLI
Config File.
```

**Comment by sudomateo** [comment]
Hello @sandangel. Your `TF_CLI_ARG_init` environment variable is incorrect.

You have this.

```
          TF_CLI_ARGS_init: '-backend-config token=${{ secrets.TFE_TOKEN }}'
```

It should be this.

```
          TF_CLI_ARGS_init: '-backend-config="token=${{ secrets.TFE_TOKEN }}"'
```

You can see a complete working example using `remote` here: https://github.com/hashicorp/terraform-github-actions/tree/master/examples/push_remote_backend_name

**Comment by sandangel** [comment]
hi @sudomateo , I tried that one as well. I already tried for couple hours before decided to file an issue here.

**Comment by sudomateo** [comment]
@sandangel I noticed in your edited comment, you are using smart quotes (`“`,`”`) instead of normal quotes (`"`,`"`). Please ensure you're using normal quotes.

I was able to successfully use this `main.tf` file.

```
terraform {
  backend "remote" {
    workspaces {
      name = "github-actions"
    }
  }
}

resource "null_resource" "example" {
  triggers = {
    value = "example"
  }
}
```

With this GitHub Actions workflow YAML file.

```
name: 'Terraform GitHub Actions'
on:
  - pull_request
jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@master
      - name: 'Terraform Format'
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_version: 0.12.13
          tf_actions_subcommand: 'fmt'
          tf_actions_comment: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: 'Terraform Init'
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_version: 0.12.13
          tf_actions_subcommand: 'init'
          tf_actions_comment: true
        env:
          TF_CLI_ARGS_init: '-backend-config="token=${{ secrets.TOKEN }}" -backend-config="organization=redacted"'
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: 'Terraform Validate'
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_version: 0.12.13
          tf_actions_subcommand: 'validate'
          tf_actions_comment: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

**Comment by sandangel** [comment]
hi, that’s because I’m typing using my ipad, but I’m pretty sure that I used the normal quote like the one you see here `{ token = \\\"${TFE_TOKEN}\\\" }`

**Comment by sudomateo** [comment]
Gotcha. I'm still not able to reproduce this. What does your `remote` backend look like?

**Comment by sandangel** [comment]
hi, thanks for quick response. I have this config for my remote backend
```hcl
terraform {
  required_version = "~> 0.12.12"
  backend remote {
    organization = "*redacted*"

    workspaces {
      name = "my-infra-network"
    }
  }
}
```

**Comment by sandangel** [comment]
hi, can you try with -backend=false?
the docs says it should work with -backend=false right?

https://www.terraform.io/docs/commands/validate.html

**Comment by sudomateo** [comment]
Still worked for me.

I only changed this.

```
TF_CLI_ARGS_init: '-backend-config="token=${{ secrets.TOKEN }}" -backend-config="organization=redacted"'
```

```
TF_CLI_ARGS_init: '-backend=false'
```

**Comment by sandangel** [comment]
hmm, this is confusing. I will try to investigate. even on my local, if I don’t have `~/.terraformrc`, the terraform validate command will fail

**Comment by sandangel** [comment]
Can you try removing the quote from your remote backend config?
`backend “remote” {` to `backend remote {`

**Comment by sudomateo** [comment]
That is a bit odd. I do not have a `~/.terraformrc` file and I can locally `init` and `validate`.

```
$ ls ~/.terraformrc
ls: cannot access '/home/redacted/.terraformrc': No such file or directory
$ terraform version
Terraform v0.12.13
$ terraform init -backend=false
Backend reinitialization required. Please run "terraform init".
Reason: Initial configuration of the requested backend "remote"

The "backend" is the interface that Terraform uses to store state,
perform operations, etc. If this message is showing up, it means that the
Terraform configuration you're using is using a custom configuration for
the Terraform backend.

Changes to backend configurations require reinitialization. This allows
Terraform to setup the new configuration, copy existing state, etc. This is
only done during "terraform init". Please run that command now then try again.

If the change reason above is incorrect, please verify your configuration
hasn't changed and try again. At this point, no changes to your existing
configuration or state have been made.


Initializing provider plugins...
- Checking for available provider plugins...
- Downloading plugin for provider "null" (hashicorp/null) 2.1.2...

The following providers do not have any version constraints in configuration,
so the latest version was installed.

To prevent automatic upgrades to new major versions that may contain breaking
changes, it is recommended to add version = "..." constraints to the
corresponding provider blocks in configuration, with the constraint strings
suggested below.

* provider.null: version = "~> 2.1"

Terraform has been successfully initialized!

You may now begin working with Terraform. Try running "terraform plan" to see
any changes that are required for your infrastructure. All Terraform commands
should now work.

If you ever set or change modules or backend configuration for Terraform,
rerun this command to reinitialize your working directory. If you forget, other
commands will detect it and remind you to do so if necessary.
$ terraform validate
Success! The configuration is valid.
```

**Comment by sudomateo** [comment]
Even with the quotes removed around `remote` I'm getting success for `validate` locally and through GitHub Actions.

**Comment by sandangel** [comment]
$ mv ~/.terraformrc ~/.terraformrc.bak

~/infra/network
$ tf init -backend=false
Initializing modules...
Downloading terraform-aws-modules/vpc/aws 2.18.0 for vpc...
- vpc in .terraform/modules/vpc/terraform-aws-modules-terraform-aws-vpc-95b970d
Backend reinitialization required. Please run "terraform init".
Reason: Initial configuration of the requested backend "remote"

The "backend" is the interface that Terraform uses to store state,
perform operations, etc. If this message is showing up, it means that the
Terraform configuration you're using is using a custom configuration for
the Terraform backend.

Changes to backend configurations require reinitialization. This allows
Terraform to setup the new configuration, copy existing state, etc. This is
only done during "terraform init". Please run that command now then try again.

If the change reason above is incorrect, please verify your configuration
hasn't changed and try again. At this point, no changes to your existing
configuration or state have been made.


Initializing provider plugins...
- Checking for available provider plugins...
- Downloading plugin for provider "aws" (hashicorp/aws) 2.34.0...

Terraform has been successfully initialized!

You may now begin working with Terraform. Try running "terraform plan" to see
any changes that are required for your infrastructure. All Terraform commands
should now work.

If you ever set or change modules or backend configuration for Terraform,
rerun this command to reinitialize your working directory. If you forget, other
commands will detect it and remind you to do so if necessary.

~/infra/network
$ tf validate
Success! The configuration is valid.


~/infra/network
$ cd ../

~/infra
? ls
README.md	Session.vim	cloudflare	cloudformation	gcp		grafana		iam		live		modules		monitoring	network		shared

~/infra
? cd live/qa1

~/infra/live/qa1
$ ls
configs_qa1.tf		ecs_services.tf		load_balancer_rules.tf	log_groups.tf		outputs.tf		target_groups.tf	variables.tf
container_definitions	iam_roles.tf		load_balancers.tf	main.tf			providers.tf		task_definitions.tf

~/infra/live/qa1
$ ls -lah
total 104
drwxr-xr-x  16 sand  staff   512B Oct 31 01:37 .
drwxr-xr-x   8 sand  staff   256B Oct 31 01:37 ..
-rw-r--r--   1 sand  staff     0B Oct 31 01:37 .gitkeep
-rw-r--r--   1 sand  staff   1.7K Oct 31 01:37 configs_qa1.tf
drwxr-xr-x   7 sand  staff   224B Oct 31 01:37 container_definitions
-rw-r--r--   1 sand  staff   5.6K Oct 31 01:37 ecs_services.tf
-rw-r--r--   1 sand  staff   215B Oct 31 01:37 iam_roles.tf
-rw-r--r--   1 sand  staff   3.9K Oct 31 01:37 load_balancer_rules.tf
-rw-r--r--   1 sand  staff   1.5K Oct 31 01:37 load_balancers.tf
-rw-r--r--   1 sand  staff   1.1K Oct 31 01:37 log_groups.tf
-rw-r--r--   1 sand  staff   2.6K Oct 31 01:37 main.tf
-rw-r--r--   1 sand  staff   516B Oct 31 01:37 outputs.tf
-rw-r--r--   1 sand  staff   138B Oct 31 01:37 providers.tf
-rw-r--r--   1 sand  staff   2.7K Oct 31 01:37 target_groups.tf
-rw-r--r--   1 sand  staff   3.2K Oct 31 01:37 task_definitions.tf
-rw-r--r--   1 sand  staff   219B Oct 31 01:37 variables.tf

~/infra/live/qa1
$ rm -rf .terraform

~/infra/live/qa1
$ tf init -backend=false
Initializing modules...
- ecs_cluster in ../../modules/z-ecs-cluster
Backend reinitialization required. Please run "terraform init".
Reason: Initial configuration of the requested backend "remote"

The "backend" is the interface that Terraform uses to store state,
perform operations, etc. If this message is showing up, it means that the
Terraform configuration you're using is using a custom configuration for
the Terraform backend.

Changes to backend configurations require reinitialization. This allows
Terraform to setup the new configuration, copy existing state, etc. This is
only done during "terraform init". Please run that command now then try again.

If the change reason above is incorrect, please verify your configuration
hasn't changed and try again. At this point, no changes to your existing
configuration or state have been made.


Initializing provider plugins...
- Checking for available provider plugins...
- Downloading plugin for provider "aws" (hashicorp/aws) 2.34.0...

Terraform has been successfully initialized!

You may now begin working with Terraform. Try running "terraform plan" to see
any changes that are required for your infrastructure. All Terraform commands
should now work.

If you ever set or change modules or backend configuration for Terraform,
rerun this command to reinitialize your working directory. If you forget, other
commands will detect it and remind you to do so if necessary.

~/infra/live/qa1
$ ls -lah
total 104
drwxr-xr-x  17 sand  staff   544B Nov  6 04:59 .
drwxr-xr-x   8 sand  staff   256B Oct 31 01:37 ..
-rw-r--r--   1 sand  staff     0B Oct 31 01:37 .gitkeep
drwxr-xr-x   4 sand  staff   128B Nov  6 04:59 .terraform
-rw-r--r--   1 sand  staff   1.7K Oct 31 01:37 configs_qa1.tf
drwxr-xr-x   7 sand  staff   224B Oct 31 01:37 container_definitions
-rw-r--r--   1 sand  staff   5.6K Oct 31 01:37 ecs_services.tf
-rw-r--r--   1 sand  staff   215B Oct 31 01:37 iam_roles.tf
-rw-r--r--   1 sand  staff   3.9K Oct 31 01:37 load_balancer_rules.tf
-rw-r--r--   1 sand  staff   1.5K Oct 31 01:37 load_balancers.tf
-rw-r--r--   1 sand  staff   1.1K Oct 31 01:37 log_groups.tf
-rw-r--r--   1 sand  staff   2.6K Oct 31 01:37 main.tf
-rw-r--r--   1 sand  staff   516B Oct 31 01:37 outputs.tf
-rw-r--r--   1 sand  staff   138B Oct 31 01:37 providers.tf
-rw-r--r--   1 sand  staff   2.7K Oct 31 01:37 target_groups.tf
-rw-r--r--   1 sand  staff   3.2K Oct 31 01:37 task_definitions.tf
-rw-r--r--   1 sand  staff   219B Oct 31 01:37 variables.tf

~/Wor/Zeh/z-infra/live/qa1 on ? master on ??  ap-northeast-1
? tf validate

Error: Required token could not be found

Make sure you configured a credentials block for app.terraform.io in your CLI
Config File.


Error: Required token could not be found

Make sure you configured a credentials block for app.terraform.io in your CLI
Config File.


Error: Required token could not be found

Make sure you configured a credentials block for app.terraform.io in your CLI
Config File.

**Comment by sudomateo** [comment]
You can also try to export `TF_LOG=TRACE` to get more information.

**Comment by sandangel** [comment]
I found this
```sh
2019/11/06 05:11:15 [TRACE] HTTP client GET request to https://checkpoint-api.hashicorp.com/v1/versions/tfe.v2.1?product=terraform
2019/11/06 05:11:15 [WARN] module.ecs_cluster: eval: *terraform.EvalValidateResource, non-fatal err: Required token could not be found: Make sure you configured a credentials block for app.terraform.io in your CLI Config File.
2019/11/06 05:11:15 [ERROR] module.ecs_cluster: eval: *terraform.EvalSequence, err: Required token could not be found: Make sure you configured a credentials block for app.terraform.io in your CLI Config File.
2019/11/06 05:11:15 [TRACE] [walkValidate] Exiting eval tree: module.ecs_cluster.data.terraform_remote_state.shared
2019/11/06 05:11:15 [TRACE] vertex "module.ecs_cluster.data.terraform_remote_state.shared": visit complete
```

I guess this is because of I'm using `data.terraform_remote_state`

**Comment by sandangel** [comment]
@sudomateo can you try with some resource that requires terraform remote state from terraform cloud?

**Comment by sudomateo** [comment]
Ah. Thank you for telling me about the `terraform_remote_state` data source. Authentication for the `terraform_remote_state` data source is not covered with the `-backend-config` option. You'll need to explicitly pass in credentials like so.

```
data "terraform_remote_state" "example" {
  backend = "remote"

  config = {
    organization = "CHANGEME"
    token        = var.remote_state_token
    workspaces = {
      name = "CHANGEME"
    }
  }
}

variable "remote_state_token" {
  type = string
}
```

Then you can pass though credentials to your GitHub Actions workflow YAML file.

```
      - name: 'Terraform Validate'
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_version: 0.12.13
          tf_actions_subcommand: 'validate'
          tf_actions_comment: true
        env:
          TF_VAR_remote_state_token: ${{ secrets.TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```
