### ISSUE TITLE
Terraform plan doesn't handle args file

### ISSUE THREAD

**Issue by JordanForeman** [hashicorp/terraform-github-actions#114]
Perhaps I'm missing something, but I can't get my `terraform plan` step to pass for the life of me. I've been trying to better understand the code that executes the plan, but my bash-fu is nearly nonexistent. Here's my setup:

```yml
      - name: Terraform Plan
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_version: 0.12.14
          tf_actions_subcommand: 'plan'
          tf_actions_working_dir: terraform
          args: '-var-file=var/default.tfvars'
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_KEY }}
          AWS_REGION: 'us-east-1'
```

I would think the relevant part is the `args` line:

```yml
args: '-var-file=var/default.tfvars'
```

I've tried just about every permutation I can think of

* `args: '-var-file=var/default.tfvars'`
* `args: '-var-file=./var/default.tfvars'`
* `args: '-var-file=./terraform/var/default.tfvars'` (in case the `working_dir` option isn't respected although [I think it should be](https://github.com/hashicorp/terraform-github-actions/blob/7881bd794c37e7670d8cf9fc954e03f8f7c778fa/src/main.sh#L77))
* `args: '-var-file="./var/default.tfvars"'` (the docs suggest wrapping in double quotes)
* etc. etc. etc.

No matter what flavor I try, `terraform plan` always complains that my variables aren't set (I don't have defaults, I'm relying on my `tfvars` file).

```bash
Error: No value for required variable

  on vars.tf line 9:
   9: variable "my_var" {

The root module input variable "my_var" is not set, and has no default
value. Use a -var or -var-file command line argument to provide a value for
this variable.
```

Is there an issue with this action (perhaps related to #110 or #109?)? Is there some specific combination of symbols I need for this to work? I'm kind of at a loss.
