### ISSUE TITLE
Working local config fails in action (aws provider, s3 backend)

### ISSUE THREAD

**Issue by ChristopherBiscardi** [hashicorp/terraform-github-actions#121]
This .tf file, which contains an aws provider and an s3 backend, fails when using the github action. If I export the env vars locally, everything works just fine.

```terraform
provider "aws" {
  version = "~> 2.0"
  region  = "us-west-2"
}

terraform {
  backend "s3" {
    bucket         = "terraform-state-bucket-sector-tools"
    key            = "terraform/tfstate"
    region         = "us-west-2"
    dynamodb_table = "terraform-locking"
    encrypt        = true
  }
}
```

The error that is commented on the PR is

> #### `terraform init` Failed
> 
> ```
> 
> Initializing the backend...
> 
> Error: No valid credential sources found for AWS Provider.
> 	Please see https://terraform.io/docs/providers/aws/index.html for more information on
> 	providing credentials for the AWS Provider
> 
> 
> ```
> 
> *Workflow: `Terraform GitHub Actions`, Action: `hashicorpterraform-github-actions2`, Working Directory: `terraform`*

The actions yml that I'm currently using is this, although it has gone through many different iterations at this point.

```yaml
name: "Terraform GitHub Actions"
on:
  - pull_request
jobs:
  terraform:
    name: "Terraform"
    runs-on: ubuntu-latest
    env:
      AWS_DEFAULT_REGION: "us-west-2"
      AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY_SECRET }}
      # TF_LOG: debug
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: "Checkout"
        uses: actions/checkout@master
      - name: "Terraform Format"
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_version: 0.12.13
          tf_actions_subcommand: "fmt"
          tf_actions_working_dir: "terraform"
      - name: "Terraform Init"
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_version: 0.12.13
          tf_actions_subcommand: "init"
          tf_actions_working_dir: "terraform"
      - name: "Terraform Validate"
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_version: 0.12.13
          tf_actions_subcommand: "validate"
          tf_actions_working_dir: "terraform"
      - name: "Terraform Plan"
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_version: 0.12.13
          tf_actions_subcommand: "plan"
          tf_actions_working_dir: "terraform"
```

---

Also notable is that everything is fine in the action if I remove the s3 backend, the error pop up once the s3 backend is introduced.
