### ISSUE TITLE
fmt doesn't post comment each time

### ISSUE THREAD

**Issue by johnkost** [hashicorp/terraform-github-actions#122]
I'm working on implementing an Action to run a `fmt` on PRs.  Following the examples provided here https://www.terraform.io/docs/github-actions/configuration/fmt.html, I have the Action running; however, it fails to post back to the PR.  

My Action:
```
name: Terraform fmt

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: git checkout
        uses: actions/checkout@v1 

      - name: Terraform fmt
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_version: 0.11.14
          tf_actions_subcommand: 'fmt'
          tf_actions_comment: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

Logs:
```
fmt: error: the following files in . are incorrectly formatted
............. (correct list produced)

fmt: info: creating JSON
fmt: info: commenting on the pull request
##[error]Docker run failed with exit code 3
```

Looking at the `fmt` code, the comment should be posted on every run: https://github.com/hashicorp/terraform-github-actions/blob/master/src/terraform_fmt.sh#L41-L67

I'm not sure if this is a GitHub issue with the comments (perhaps rate limit issues?) or with the this Action.  Rather than redirecting to `/dev/null`, checking the request code and outputting a message would provide more insight to this.

Code in question (https://github.com/hashicorp/terraform-github-actions/blob/master/src/terraform_fmt.sh#L66):
```
echo "${fmtPayload}" | curl -s -S -H "Authorization: token ${GITHUB_TOKEN}" --header "Content-Type: application/json" --data @- "${fmtCommentsURL}" > /dev/null
```
