### ISSUE TITLE
GCS Backend

### ISSUE THREAD

**Issue by rabun788** [hashicorp/terraform-github-actions#130]
I am having trouble getting GCS to work.

In my repo:
```
terraform {
  backend "gcs" {
    project = "sandbox"
    bucket  = "terrafrom-sandbox"
    prefix  = "terraform/state"
    credentials = "/sandbox-206f5e06136d.json"
  }
}
```
```
      - name: 'Checkout'
        uses: actions/checkout@master
        with:
          path: main

      - name: 'Terraform Init'
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_version: 0.12.18
          tf_actions_subcommand: 'init'
          args: '-backend-config="credentials=${{ secrets.BRO }}"'
        env: 
          BRO: ${{ secrets.GCP_SANDBOX_KEY }}
```
I have tried all types of iterations according to the docs. 
None of them work for me.
This configuration was the closest i got, but it still doesn't connect to the backend GCS bucket.

**Comment by raj-saxena** [comment]
Hi @rabun788 ,

I was able to configure the gcs backend by using the [setup-gcloud](https://github.com/GoogleCloudPlatform/github-actions/tree/master/setup-gcloud) action before running terraform steps.
Here's the snippet I used:
```yaml
      - name: Login to GCP
        uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          version: '281.0.0'
          service_account_key: ${{ secrets.GCS_TERRAFORM_GITHUB_SA }}
          export_default_credentials: true
```
where `GCS_TERRAFORM_GITHUB_SA` is the base64encoded json service-account key.
