### ISSUE TITLE
Validate Action Fails with Missing required argument

### ISSUE THREAD

**Issue by rnason** [hashicorp/terraform-github-actions#133]
I have tried both with passing a var defining a valid AWS region, and without, both error

# Output 

-----

Run hashicorp/terraform-github-actions@master
"/home/runner/work/ActionsTest/ActionsTest":"/github/workspace" 488dfb:416b761938e34ef6b3a34a55af4e54e4 -var=region="us-east-1"
Checking the latest version of Terraform
Downloading Terraform v0.12.20
Successfully downloaded Terraform v0.12.20
Unzipping Terraform v0.12.20
Successfully unzipped Terraform v0.12.20
validate: info: validating Terraform configuration in .
validate: error: failed to validate Terraform configuration in .

Warning: The -var and -var-file flags are not used in validate. Setting them has no effect.

These flags will be removed in a future version of Terraform.

Error: Missing required argument

The argument "region" is required, but was not set.

##[error]Docker run failed with exit code 1

# Actions YML File

---------

name: Terraform Checks
on:
  # Trigger the workflow on push or pull request on the master branch only
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  terraform:
    name: Terraform Checks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Terraform Format
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_version: latest
          tf_actions_subcommand: 'fmt'
          tf_actions_working_dir: '.'
          tf_actions_comment: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Terraform Init
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_version: latest
          tf_actions_subcommand: 'init'
          tf_actions_working_dir: '.'
          tf_actions_comment: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Terraform Validate
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_version: latest
          tf_actions_subcommand: 'validate'
          tf_actions_working_dir: '.'
          tf_actions_comment: true
          args: '-var=region="us-east-1"'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Terraform Plan
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_version: latest
          tf_actions_subcommand: 'plan'
          tf_actions_working_dir: 'example/'
          tf_actions_comment: true
          args: '-var=region="us-east-1"'
        env:
          TF_VAR_region: 'us-east-1'
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

**Comment by sudomateo** [comment]
Hello,

The `terraform validate` command does not take `-var` as an argument. Source: https://www.terraform.io/docs/commands/validate.html

What is the `region` variable meant to be used for? For the `backend` block? If so, you should probably pass the variable to the `terraform init` command instead using the `-backend-config` argument.

**Comment by rnason** [comment]
I am simply trying to get the validate github action working. Without passing anything the action fails

Checking the latest version of Terraform
Downloading Terraform v0.12.20
Successfully downloaded Terraform v0.12.20
Unzipping Terraform v0.12.20
Successfully unzipped Terraform v0.12.20
validate: info: validating Terraform configuration in .
validate: error: failed to validate Terraform configuration in .

Error: Missing required argument

The argument "region" is required, but was not set.


Validate shouldn't require any variables to be set, and interestingly I am not even using a region variable within the module, so it shouldn't require it at all.

**Comment by sudomateo** [comment]
Validate only requires that the backend is initialized unless `terraform init -backend=false` was executed. Would you be able to provide the output with `TF_LOG=TRACE` set as well as your redacted Terraform files that are being used? It seems that a resource is expecting an argument named `region` to be configured and that's why `validate` is throwing this error.

**Comment by rnason** [comment]
I was able to finally find some time to circle back around to this, and corrected the issue with the following config:

```
name: 'Terraform Lint'
on:
  # Trigger the workflow on push or pull request on the master branch only
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
env:
  tf_version: 'latest'
  tf_working_dir: './example'
jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@master
      - name: 'Terraform Format'
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_version: ${{ env.tf_version }}
          tf_actions_subcommand: 'fmt'
          tf_actions_working_dir: ${{ env.tf_working_dir }}
          tf_actions_comment: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: 'Terraform Init'
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_version: ${{ env.tf_version }}
          tf_actions_subcommand: 'init'
          tf_actions_working_dir: ${{ env.tf_working_dir }}
          tf_actions_comment: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          AWS_ACCESS_KEY_ID: ${{ secrets.XXXX }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.XXXX }}
      - name: 'Terraform Validate'
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_version: ${{ env.tf_version }}
          tf_actions_subcommand: 'validate'
          tf_actions_working_dir: ${{ env.tf_working_dir }}
          tf_actions_comment: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: 'Terraform Plan'
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_version: ${{ env.tf_version }}
          tf_actions_subcommand: 'plan'
          tf_actions_working_dir: ${{ env.tf_working_dir }}
          tf_actions_comment: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          AWS_ACCESS_KEY_ID: ${{ secrets.XXXX }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.XXXX }}
          TF_CLI_ARGS_plan: '--var-file=env.tfvars'
```
