### ISSUE TITLE
"Too many command line arguments. Configuration path expected." in Terraform-github-actions

### ISSUE THREAD

**Issue by AdminTurnedDevOps** [hashicorp/terraform-github-actions#140]
Hey all,

Wondering if anyone has seen this before. Whenever I try to pass in secrets via `-var` args in Terraform via GitHub actions, I get the failure "Too many command line arguments. Configuration path expected.". 

I know it's due to the secret because if I try passing the password in via plain text, it works just fine. Take a look at my code below and let me know if I'm being silly :)

```
name: Terraform deploy to Azure

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: "Checkout"
        uses: actions/checkout@master

      - name: "Terraform Init"
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_version: 0.12.13
          tf_actions_subcommand: "init"

      - name: "Terraform Plan"
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_version: 0.12.13
          tf_actions_subcommand: "plan"
          args: -var "client_secret=${{ secrets.clientSecret }}"

      - name: "Terraform Apply"
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_version: 0.12.13
          tf_actions_subcommand: "apply"
          args: -var="client_secret=${{ secrets.clientSecret }}"
```

### Expected outcome
The `-var` argument picks up the `clientSecret` from GitHub secrets

### Current outcome
I receive an error stating ;
```
Too many command line arguments. Configuration path expected.

##[error]Docker run failed with exit code 1
```

### What's happening when Terraform plan runs
When I see the output, it shows `-var=client_secret="*** secrets.clientSecret ***"` which clearly states that the secret isn't being picked up.
