### ISSUE TITLE
How can I configure secrets.GITHUB_TOKEN ?

### ISSUE THREAD

**Issue by ganesane** [hashicorp/terraform-github-actions#141]
How will I configure the AWS credentials using GITHUB_TOKEN ?
> env:
>           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

 I am getting below error.

`Error: No valid credential sources found for AWS Provider.
	Please see https://terraform.io/docs/providers/aws/index.html for more information on
	providing credentials for the AWS Provider
`

**Comment by canelkatmis** [comment]
Iamnot sure you can configure AWS credentials using github_token. But default way is adding env and secrets as:
```
          AWS_ACCESS_KEY_ID:      ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY:  ${{ secrets.AWS_SECRET_ACCESS_KEY }}
```

**Comment by ganesane** [comment]
But in the Readme section, they have mentioned  **GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}** So I thought there is some other way to include the end variables.  Am I missing something?

steps:
      - name: 'Checkout'
        uses: actions/checkout@master
      - name: 'Terraform Format'
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_version: 0.12.13
          tf_actions_subcommand: 'fmt'
          tf_actions_working_dir: '.'
          tf_actions_comment: true
     **env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}**

**Comment by sudomateo** [comment]
Hello @ganesane. The [GitHub Actions documentation](https://help.github.com/en/actions/automating-your-workflow-with-github-actions/creating-and-using-encrypted-secrets#using-encrypted-secrets-in-a-workflow) shows how to work with secrets.

As @canelkatmis stated, your YAML file can contain the following to pass the required environment variables to the AWS provider.

```
name: 'Terraform GitHub Actions'
on:
  - pull_request
jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@master
      - name: 'Terraform Init'
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_version: 0.12.13
          tf_actions_subcommand: 'init'
          tf_actions_working_dir: '.'
          tf_actions_comment: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
```

This will require that you configure secrets on your repository by navigating to the repository Settings > Secrets location.

The README includes lines like this.

```
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

To show that the `GITHUB_TOKEN` environment variable is expected in these steps.
