### ISSUE TITLE
terraform plan fails with subdirectory

### ISSUE THREAD

**Issue by hazcod** [hashicorp/terraform-github-actions#154]
**Description**: Seems that `terraform init` in my subdirectory creates a `.terraform/` directory that is owned by root with permissions `drwxr-xr-x`, which fails the rest of the actions (?).

**CI/CD Run**: https://github.com/ironPeakServices/infrastructure/runs/497185759
**Error**:  
```
Error: Could not satisfy plugin requirements
Plugin reinitialization required. Please run "terraform init".

Error: provider.kubernetes: no suitable version installed
  version requirements: "(any version)"
  versions installed: none

Error: provider.helm: no suitable version installed
  version requirements: "(any version)"
  versions installed: none
```

**Action**:
```yaml
    - name: Terraform - Init
      uses: hashicorp/terraform-github-actions@v0.7.1
      with:
        tf_actions_subcommand: "init"
        tf_actions_version: "latest"
        tf_actions_working_dir: terraform/
        
    - run: ls -alh . terraform/

    - name: Terraform - Validate
      uses: hashicorp/terraform-github-actions@v0.7.1
      with:
        tf_actions_subcommand: "validate"
        tf_actions_version: "latest"
        tf_actions_working_dir: terraform/
  
    - name: Terraform - Plan
      uses: hashicorp/terraform-github-actions@v0.7.1
      with:
        tf_actions_subcommand: "plan"
        tf_actions_version: "latest"
        tf_actions_working_dir: terraform/
      env:
        TF_LOG: WARN
        TF_CLI_ARGS: "-state=state/terraform.tfstate"
        TF_ACTION_COMMENT: false
        ....

```

**Extra**: `ls -alh . terraform` seems to show a `.terraform` being created correctly:
```
Run ls -alh . terraform/
.:
total 56K
drwxr-xr-x 8 runner docker 4.0K Mar 10 07:32 .
drwxr-xr-x 3 runner docker 4.0K Mar 10 07:30 ..
drwxr-xr-x 2 runner docker 4.0K Mar 10 07:32 .dependabot
drwxr-xr-x 8 runner docker 4.0K Mar 10 07:32 .git
drwxr-xr-x 3 runner docker 4.0K Mar 10 07:32 .github
-rw-r--r-- 1 runner docker   84 Mar 10 07:32 .gitignore
-rw-r--r-- 1 runner docker  138 Mar 10 07:32 .whitesource
-rw-r--r-- 1 runner docker  12K Mar 10 07:32 LICENSE
-rw-r--r-- 1 runner docker  868 Mar 10 07:32 README.md
drwxr-xr-x 2 runner docker 4.0K Mar 10 07:32 helm
drwxr-xr-x 5 runner docker 4.0K Mar 10 07:32 kubernetes
drwxr-xr-x 5 runner docker 4.0K Mar 10 07:32 terraform

terraform/:
total 36K
drwxr-xr-x 5 runner docker 4.0K Mar 10 07:32 .
drwxr-xr-x 8 runner docker 4.0K Mar 10 07:32 ..
drwxr-xr-x 4 root   root   4.0K Mar 10 07:32 .terraform
-rw-r--r-- 1 runner docker  503 Mar 10 07:32 main.tf
drwxr-xr-x 6 runner docker 4.0K Mar 10 07:32 modules
-rw-r--r-- 1 runner docker  655 Mar 10 07:32 providers.tf
-rw-r--r-- 1 runner docker  133 Mar 10 07:32 resources.tf
drwxr-xr-x 3 runner docker 4.0K Mar 10 07:32 state
-rw-r--r-- 1 runner docker  530 Mar 10 07:32 variables.tf
```
