### ISSUE TITLE
Plan and Apply do not consider Remote State

### ISSUE THREAD

**Issue by ahacke** [hashicorp/terraform-github-actions#166]
Hi,

I am using terraform to configure our github organization via the github provider in a pull-request based workflow with github actions. The state file is stored in a remote state in an azure blob storage with private access.

Simplified config:
```
provider "github" {
  organization = "myorg"
  version      = "2.6.1"
}

terraform {
  backend "azurerm" {
    storage_account_name = "myorg"
    container_name       = "tfstate"
    key                  = "terraform.tfstate"
  }
}

resource "github_repository" "myrepo" {
  name = "myrepo"
}

resource "github_membership" "membership" {
  username = myuser
  role     = admin
}
```

Github PR workflow
```
# Template Source: https://github.com/hashicorp/terraform-github-actions
name: 'Terraform Checks on Pull-Request'
on:
  pull_request:
    branches:
      - 'master'
env:
  tf_version: 'latest'
  tf_working_dir: 'src'
jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@master
      - name: 'Terraform Init'
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_version: ${{ env.tf_version }}
          tf_actions_subcommand: 'init'
          tf_actions_working_dir: ${{ env.tf_working_dir }}
          tf_actions_comment: true
          args: '-backend-config="access_key=${{ secrets.AZURE_ACCESS_KEY }}"'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: 'Terraform Format'
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_version: ${{ env.tf_version }}
          tf_actions_subcommand: 'fmt'
          tf_actions_working_dir: ${{ env.tf_working_dir }}
          tf_actions_comment: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: 'Terraform Validate'
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_version: ${{ env.tf_version }}
          tf_actions_subcommand: 'validate'
          tf_actions_working_dir: ${{ env.tf_working_dir }}
          tf_actions_comment: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: 'Terraform Plan'
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_version: ${{ env.tf_version }}
          tf_actions_subcommand: 'plan'
          tf_actions_working_dir: ${{ env.tf_working_dir }}
          tf_actions_comment: true
        env:
          GITHUB_TOKEN: ${{ secrets.PAT}}
```

The user and the repository already exist in the github organization and are available in the remot estate. The repository was imported via `terraform import github_repository.myrepo myrepo`.

**Actual**
Locally, running `tf plan` puts out the expected changes.
```
Terraform will perform the following actions:

  # github_repository.myrepo will be updated in-place
  ~ resource "github_repository" "myrepo" {
        allow_merge_commit     = true
        allow_rebase_merge     = true
        allow_squash_merge     = true
        archived               = false
        auto_init              = false
        default_branch         = "master"
        delete_branch_on_merge = false
        etag                   = "...."  (obfuscated)
        full_name              = "myorg/myrepo"
        git_clone_url          = "git://github.com/myorg/myrepo.git"
      - has_downloads          = true -> null
      - has_issues             = true -> null
        has_projects           = false
      - has_wiki               = true -> null
        html_url               = "https://github.com/myorg/myrepo"
        http_clone_url         = "https://github.com/myorg/myrepo.git"
        id                     = "myrepo"
        is_template            = false
        name                   = "myrepo"
        node_id                = "...=" (obfuscated)
      - private                = true -> null
        ssh_clone_url          = "git@github.com:myorg/myrepo.git"
        svn_url                = "https://github.com/myorg/myrepo"
        topics                 = []
    }

Plan: 0 to add, 1 to change, 0 to destroy.
```

If the plan is run on a pull request with the same configuration, the following output is generated:
`tf init`:
```
init: info: initializing Terraform configuration in src
init: info: successfully initialized Terraform configuration in src

Initializing the backend...

Successfully configured the backend "azurerm"! Terraform will automatically
use this backend unless the backend configuration changes.

Initializing provider plugins...
- Checking for available provider plugins...
- Downloading plugin for provider "github" (hashicorp/github) 2.6.1...

Terraform has been successfully initialized!
```
`tf plan`
```
Terraform will perform the following actions:

  # github_repository.myrepo will be created
  + resource "github_repository" "myrepo " {
      + allow_merge_commit     = true
      + allow_rebase_merge     = true
      + allow_squash_merge     = true
      + archived               = false
      + default_branch         = (known after apply)
      + delete_branch_on_merge = false
      + etag                   = (known after apply)
      + full_name              = (known after apply)
      + git_clone_url          = (known after apply)
      + html_url               = (known after apply)
      + http_clone_url         = (known after apply)
      + id                     = (known after apply)
      + name                   = "myrepo"
      + node_id                = (known after apply)
      + ssh_clone_url          = (known after apply)
      + svn_url                = (known after apply)
    }

Plan: 1 to add, 0 to change, 0 to destroy.
```

Additionally, if the pull-request is merged, another workflow is triggered, which is trying to apply the current configuration. Also the `tf apply` is adding this repository but obviously fails as it already exists.

Error of `tf apply`:
```
 POST https://api.github.com/orgs/myorg/repos: 422 Repository creation failed. [{Resource:Repository Field:name Code:custom Message:name already exists on this account}]

  on main.tf line 3, in resource "github_repository" "myrepo":
   3: resource "github_repository" "myrepo" {
```
Also, `tf apply` updates the remote state and removes the imported repository configuration.

**Expected**
The expectation is, that locally and remotely via the github actions, the plan is the same and is only changing the settings as described above.
