### ISSUE TITLE
gcloud command not found

### ISSUE THREAD

**Issue by mihaisee** [hashicorp/terraform-github-actions#167]
Hi, 

I have a workflow that uses [terraform gke module](https://registry.terraform.io/modules/terraform-google-modules/kubernetes-engine/google/8.1.0) for creating a google kubernetes engine cluster.
All is good until it executes the `apply`, because the module uses a script that needs `gcloud` to wait for cluster to reconcile...

I have used the action: https://github.com/GoogleCloudPlatform/github-actions/tree/master/setup-gcloud to setup `gcloud` and this works perfectly with `js` actions.

Since this is a `docker` action I assume this is the reason why it's not working, because the `gcloud` cli is installed on the host runner and terraform action runs inside docker (maybe I'm wrong)

Is there an option to get the gcloud configured correctly inside `terraform-github-actions`?

Here is an example of what I'm using in my workflow:

```yaml
- name: 'Checkout'
  uses: actions/checkout@v2
- name: 'Setup gcloud'
  uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
  with:
    version: '289.0.0'
    service_account_key: ${{ some_secret_key }}
- name: 'Terraform Apply'
  uses: hashicorp/terraform-github-actions@master
  with:
    tf_actions_version: 0.12.24
    tf_actions_subcommand: 'apply'
    tf_actions_comment: true
  env:
    TF_VAR_gcp_service_account_key: ${{ some_account_key }}
```

The error received is: `terraform-google-kubernetes-engine-8.1.0/scripts/wait-for-cluster.sh: line 28: gcloud: command not found`

Thanks
