### ISSUE TITLE
Rewrite in golang

### ISSUE THREAD

**Issue by lkysow** [hashicorp/terraform-github-actions#24]
The current bash scripts have gotten too long. They are now quite complex, hard to test, and have lots of duplication.

I think it would be best to rewrite the actions in golang and properly test them.

**Comment by hazcod** [comment]
Bonus points if we would be able to re-use the same image.
My Action builds three separate images, but those are essentially the same except for the entrypoint bash script.

**Comment by sudomateo** [comment]
@hazcod GitHub will build a new container image for each `jobs.<job_id>` defined in your yaml file.

So given the following.

```
jobs:
  format_one:
    name: 'Terraform Actions (one)'
    runs-on: ubuntu-latest
    steps:
      - name: 'Terraform Format'
        uses: hashicorp/terraform-github-actions/fmt@master
  format_two:
    name: 'Terraform Actions (two)'
    runs-on: ubuntu-latest
    steps:
      - name: 'Terraform Format'
        uses: hashicorp/terraform-github-actions/fmt@master
```

The container image for `hashicorp/terraform-github-actions/fmt@master` will be built twice. Once in the `format_one` job and again in the `format_two` job. The only time a container image will be reused if if there are multiple `steps` in a given job that reference the same container image.

If this were to be rewritten in golang, which I do want to do at some point, it would be better to provide a pre-built Docker image than to have GitHub Actions run `docker build` for each new `Dockerfile`. Something like this.

```
jobs:
  example:
    steps:
      - name: 'The Golang rewrite (example)'
        uses: docker://tf-actions-golang:latest
```

I'm working on a refactor with bash that will decrease use of repeated code and hopefully serve as an intermediate point between this `entrypoint.sh` per action and a complete rewrite in golang.
