### ISSUE TITLE
Git SSH cloning fails

### ISSUE THREAD

**Issue by Vlaaaaaaad** [hashicorp/terraform-github-actions#39]
When using the `init` action as defined below:
```
name: Terraform

on: [push]

jobs:

  Formatting:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@master
    
    - name: Formatting
      uses: hashicorp/terraform-github-actions/fmt@v0.3.5

  Validation:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@master

    - name: Init
      uses: hashicorp/terraform-github-actions/init@v0.3.5
    
    - name: Validation
      uses: hashicorp/terraform-github-actions/validate@v0.3.5
      env:
        AWS_DEFAULT_REGION: us-east-1
```
the `init` step fails due to not being able to clone the repo:
```
[DEBUG] Using modified User-Agent: Terraform/0.12.6 terraform-github-actions/1.0
Initializing modules...
Downloading git@github.com:terraform-aws-modules/terraform-aws-eks.git?ref=v5.0.0 for eks...

Error: Failed to download module

Could not download module "eks" (eks.tf:1) source code from
"git@github.com:terraform-aws-modules/terraform-aws-eks.git?ref=v5.0.0": error
downloading
'ssh://git@github.com/terraform-aws-modules/terraform-aws-eks.git?ref=v5.0.0':
/usr/bin/git exited with 128: Cloning into '.terraform/modules/eks'...
Host key verification failed.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

Any ideas about how this could be fixed? 

The npm action has [a comment suggesting some bash magic to insert SSH keys](https://github.com/actions/npm/issues/25#issuecomment-486818213). Maybe something along these lines?

I am new to GitHub actions so I may be totally missing something.

**Comment by sudomateo** [comment]
So this is not an issue necessarily. SSH operations will fail if there are no private SSH keys on the container being used. Adding an option to inject an SSH private key into the container isn't necessarily out of the question, but would definitely take away from the scope of this project. Then dealing within encrypted private SSH keys also becomes a concern.

**Comment by abatilo** [comment]
Shouldn't ssh key injection be in scope? Otherwise it'll be impossible to do an init when you have an SSH sourced module.

**Comment by sudomateo** [comment]
@abatilo I never said it was out of scope, only that it will take away from the scope of this project. If it was possible to use GitHub Actions inputs inside the `Dockerfile`, implementing this would be trivial. Since that's not the case, implementing this will require writing extra code to handle SSH private key injection and decrypting the SSH private key if it's encrypted. It's something that will be considered, but there are other issues that I believe should be tackled first. If you have time to work on this, pull requests would be appreciated.

**Comment by abatilo** [comment]
Oh! I'm sorry, I misinterpreted what you meant by "taking away scope". I'd love to contribute if I could get a little guidance on what needs to be done

**Comment by Vlaaaaaaad** [comment]
Some notes on this since I kept working:
- Docker-based GitHub Actions are sloooooow. Since there's no caching they are so so slow. It's better to just install Terraform yourself and use it like that
- there are actions that load SSH keys from GitHub Secrets and that even expose it to Docker if you are using it( SSH_AGENT_SOCK)

All these things and other learnings will be shared in an open-source repo sometime soon™️( I wanted to do it this week but other things got in the way).

**Comment by Vlaaaaaaad** [comment]
Scratch that, I found no way to get the `SSH_AGENT_SOCK` to work. Not manually, nor with [webfactory/ssh-agent@v0.1.1](https://github.com/marketplace/actions/webfactory-ssh-agent).

I am going forward with manual SSH setup + Terraform install for all repos that require private modules.

**Comment by thorker** [comment]
@Vlaaaaaaad 
I think the problem is the missing possibility to extend prepared docker actions with volumes, so  you can inject your ssh_auth_sock and set the env var to the mounted volume.

I am waiting for this feature to be implemented by GitHub.

**Comment by abatilo** [comment]
This is what I ended up doing to clone a private module, and it definitely worked even if a bit wonky.
```
    - name: Create .ssh directory
      uses: actions/bin/sh@master
      with:
        args: '"mkdir -p $HOME/.ssh"'
    - name: Write SSH key to disk
      uses: actions/bin/sh@master
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      with:
        args: '"echo \"$SSH_PRIVATE_KEY\" > $HOME/.ssh/id_rsa"'
    - name: Set SSH key permissions
      uses: actions/bin/sh@master
      with:
        args: '"chmod 400 $HOME/.ssh/id_rsa"'
    - name: Terraform Init
      uses: hashicorp/terraform-github-actions/init@v0.4.0
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GIT_SSH_COMMAND: "ssh -o StrictHostKeyChecking=no -i $HOME/.ssh/id_rsa"
        TF_ACTION_WORKING_DIR: ${{ matrix.folders }}
```
