### ISSUE TITLE
Add support for terraform destroy

### ISSUE THREAD

**Issue by canelkatmis** [hashicorp/terraform-github-actions#43]
Anyone that already created an infra via terraform-github-actions should be destroy this infra via terraform-github-actions.

**Comment by sudomateo** [comment]
I agree that this should should be added, although I'll admit there are other issues that are more pressing at the moment.

**Comment by canelkatmis** [comment]
I tried and applied this feature in my branch. If you are OK, I can send a PR quickly for this

**Comment by ns-phennessy** [comment]
what would the workflow for this look like? 

Like someone deletes a stack file and then the action will determine that an existing stack was deleted? I guess i dont totally understand how that would work

**Comment by sudomateo** [comment]
The workflow would essentially be `terraform plan -out=output.tfplan && terraform apply output.tfplan`. Sorry for the brevity, I'm mobile for the next few days.

**Comment by igordcsouza** [comment]
One workflow that works for me is:
We are deploying containers on ECS Fargate and we start to deploy review apps.
So when someone opens a PR we want do raise a whole new environment, so the client/PO/whatever can use the feature and see for yourself if it's good to go for production.
After merging it, we need to destroy this environment and that's where the destroy cames up. 
I have changed a lite bit the `plan` to create a new workspace when try to select someone that didn't exist, but it is for another issue :)

**Comment by mr-smithers-excellent** [comment]
@sudomateo Will `destroy` be a bit more straight forward to implement after the recent refactoring?

**Comment by nikolay-bocharov** [comment]
You can ''codearound'' this problem like this
```
- name: 'Terraform Plan Destroy'
uses: hashicorp/terraform-github-actions@master
with:
  tf_actions_version: latest
  tf_actions_subcommand: 'plan'
  args: '-destroy -out=./destroy-plan'
- name: 'Terraform Apply Destroy'
uses: hashicorp/terraform-github-actions@master
with:
  tf_actions_version: latest
  tf_actions_subcommand: 'apply'  
  args: './destroy-plan'

```
