### ISSUE TITLE
terraform-init do not support TF_ACTION_WORKSPACE 

### ISSUE THREAD

**Issue by hideto0710** [hashicorp/terraform-github-actions#46]
## config
```
- name: terraform-init
  uses: hashicorp/terraform-github-actions/init@v0.3.6
  env:
    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    TF_ACTION_WORKING_DIR: .
    TF_ACTION_WORKSPACE: production
    TF_ACTION_TFE_TOKEN: ${{ secrets.TF_ACTION_TFE_TOKEN }}
```
## Log
```
Run hashicorp/terraform-github-actions/init@v0.3.6
/usr/bin/docker run --name ec5e59344abd5d0741c0b5dfca8bc09b44ad_9a9c0b --label 20ec5e --workdir /github/workspace --rm -e GITHUB_TOKEN -e TF_ACTION_WORKING_DIR -e TF_ACTION_WORKSPACE -e TF_ACTION_TFE_TOKEN -e HOME -e GITHUB_REF -e GITHUB_SHA -e GITHUB_REPOSITORY -e GITHUB_ACTOR -e GITHUB_WORKFLOW -e GITHUB_HEAD_REF -e GITHUB_BASE_REF -e GITHUB_EVENT_NAME -e GITHUB_WORKSPACE -e GITHUB_ACTION -e GITHUB_EVENT_PATH -e RUNNER_OS -e RUNNER_TOOL_CACHE -e RUNNER_TEMP -e RUNNER_WORKSPACE -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" -v "/home/runner/work/wevox-terraform/wevox-terraform":"/github/workspace" 20ec5e:59344abd5d0741c0b5dfca8bc09b44ad
2019/08/29 13:30:36 [DEBUG] Using modified User-Agent: Terraform/0.12.7 terraform-github-actions/1.0

Initializing the backend...

Successfully configured the backend "remote"! Terraform will automatically
use this backend unless the backend configuration changes.

The currently selected workspace (default) does not exist.
  This is expected behavior when the selected workspace did not have an
  existing non-empty state. Please enter a number to select a workspace:
  
  1. production
  2. staging

  Enter a value: 

Error: Failed to select workspace: input not a valid number
##[error]Docker run failed with exit code 1
```

**Comment by hideto0710** [comment]
related https://github.com/hashicorp/terraform/issues/21393 ??

I could fix by using `TF_WORKSPACE`

**Comment by brianpham** [comment]
I am running into a similar issue for plan

```
    - name: Terraform - Plan
      uses: hashicorp/terraform-github-actions/plan@v0.3.7
      env:
        TF_ACTION_WORKING_DIR: "terraform"
        TF_ACTION_WORKSPACE: "dev"
        TF_ACTION_TFE_TOKEN: ${{ secrets.TF_ACTION_TFE_TOKEN}}
```

```
/usr/bin/docker run --name df7dc0bca6635c9de43138489c0725ad4b8cb_696079 --label 0df7dc --workdir /github/workspace --rm -e TF_ACTION_WORKING_DIR -e TF_ACTION_WORKSPACE -e TF_ACTION_TFE_TOKEN -e HOME -e GITHUB_REF -e GITHUB_SHA -e GITHUB_REPOSITORY -e GITHUB_ACTOR -e GITHUB_WORKFLOW -e GITHUB_HEAD_REF -e GITHUB_BASE_REF -e GITHUB_EVENT_NAME -e GITHUB_WORKSPACE -e GITHUB_ACTION -e GITHUB_EVENT_PATH -e RUNNER_OS -e RUNNER_TOOL_CACHE -e RUNNER_TEMP -e RUNNER_WORKSPACE -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" -v "/home/runner/work/infra/infra":"/github/workspace" 0df7dc:0bca6635c9de43138489c0725ad4b8cb
workspaces not supported
```

**Comment by brianpham** [comment]
init is working for me though

```
    - name: Terraform - Init
      uses: hashicorp/terraform-github-actions/init@v0.3.7
      env:
        TF_ACTION_WORKING_DIR: "terraform"
        TF_ACTION_WORKSPACE: "dev"
        TF_ACTION_TFE_TOKEN: ${{ secrets.TF_ACTION_TFE_TOKEN}}
```
