### ISSUE TITLE
curl issue when running terraform plan action v0.4.0 using the github provider

### ISSUE THREAD

**Issue by stevenhayes** [hashicorp/terraform-github-actions#63]
We are receiving the following error when running `hashicorp/terraform-github-actions/plan@v0.4.0`. This is preceded by the `init` action of the same version, which does not error.

```
Plan: 72 to add, 0 to change, 0 to destroy.
------------------------------------------------------------------------
curl: (6) Could not resolve host: null
##[error]Docker run failed with exit code 6
```

Note, we are using the Terraform GitHub Provider as follows `* provider.github: version = "~> 2.2"`.

Also, it appears that a local state file is being used, rather than the shared s3 backend, as the `plan` action reports it will add all the terraform resources (72 of them) that have been previously set up. I can't share details of the actual github resources as they contain user details...

**Comment by sudomateo** [comment]
Hello,

Can you share the `.github/workflows/*.yml` file used to run this job?

**Comment by stevenhayes** [comment]
Sure

```
name: Terraform-Plan

on:
  push:
    branches:
      - master

jobs:
  apply:
    name: Terraform Plan Job

    runs-on: ubuntu-18.04
    
    steps:
    - name: Checkout codebase
      uses: actions/checkout@v1

    - name: Terraform - Init
      uses: hashicorp/terraform-github-actions/init@v0.4.0
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        TF_ACTION_WORKING_DIR: "./src/iac/providers/github/global"

    - name: Terraform - Plan
      uses: hashicorp/terraform-github-actions/plan@v0.4.0
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        ELEVATED_GITHUB_TOKEN: ${{ secrets.ELEVATED_GITHUB_TOKEN }}
        TF_ACTION_WORKING_DIR: "./src/iac/providers/github/global"
      with:
        args: -var="elevated_github_token=$ELEVATED_GITHUB_TOKEN"
```
