### ISSUE TITLE
Support 3rd party providers

### ISSUE THREAD

**Issue by KushalP** [hashicorp/terraform-github-actions#74]
Allow integrating a 3rd party provider into the run for this action, e.g. https://github.com/Mongey/terraform-provider-kafka

**Comment by sudomateo** [comment]
I'm trying to think of the best way to make this work. 3rd party providers need to be in one of [these locations](https://www.terraform.io/docs/extend/how-terraform-works.html#plugin-locations) for `terraform` to pick it up. 

I believe the best way to handle this would be pulling the compiled 3rd party provider binary into your GitHub Actions workspace in the `terraform.d/plugins/linux_amd64` directory relative to your repository's root. Maybe adding another step is the best course of action here since this is separate from invoking `terraform`.

**Comment by KushalP** [comment]
Is it possible to add a URL where a release can be downloaded if an argument is provided to a custom provider URL?

Annoyingly, some providers wrap everything as a tarball. So we'll need to consider this.

**Comment by mmindenhall** [comment]
@sudomateo, unless I'm misunderstanding, a 3rd party plugin would need to be installed inside the docker container that is running the `terraform-github-actions` code.  That would add a lot of complexity to the existing implementation.

If it's possible to refactor `terraform-github-actions` to be a [JavaScript action](https://help.github.com/en/actions/building-actions/about-actions#types-of-actions), this problem would go away.  The plugins could then be installed by separate JavaScript actions (e.g., similar to [this one that installs python poetry](https://github.com/dschep/install-poetry-action)), and would get picked up automatically when `terraform-github-actions` executes.

**Comment by sudomateo** [comment]
@mmindenhall I believe the `GITHUB_WORKSPACE`is preserved between steps. It's how the checkout operation is able to be a separate step. It's also how the `.terraform` directory can persist between the `init` and `plan` operations.

Technically speaking, all a JavaScript Action does is run the commands on the VM instead of inside the container. The same effect can be achieved without creating a JavaScript Action using the following YAML.

```
name: 'Terraform Examples'
on:
  - pull_request
jobs:
  vm:
    name: 'Terraform (vm)'
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout Repo'
        uses: actions/checkout@master
      - name: 'Install Terraform'
        run: |
          mkdir -p ${HOME}/bin
          export PATH="${HOME}/bin:${PATH}"
          curl -L -o /tmp/terraform.zip https://releases.hashicorp.com/terraform/0.12.20/terraform_0.12.20_linux_amd64.zip
          unzip -o -d ${HOME}/bin /tmp/terraform.zip
      - name: 'Execute Terraform Format'
        run: terraform fmt -check=true -write=false -diff
      - name: 'Execute Terraform Init'
        run: terraform init -backend-config="token=${{ secrets.TF_API_TOKEN }}" -backend-config="organization=redacted"
```

That being said, there are no plans to refactor this into a JavaScript Action at this time.

**Comment by augustgerro** [comment]
What If I will create `terraform.d` folder in my project?
I guess it is not the best way if in local environment binary was built for either of non-Linux environment (darwin, frebsb, windows). 

What if this action will take as argument URL for cloning plugin and build it as part of the pipeline?

**Comment by thomas-riccardi** [comment]
After some struggle with the actions executed in docker containers I finally found a working solution:
(writing in `$HOME/.terraform.d/plugins` doesn't work as the `$HOME` is *not* mounted in the `hashicorp/terraform-github-actions` container)
Add this step before the `terraform init` one:
```yaml
      - name: 'Install terraform-provider-k8s'
        run: |
          mkdir -p ${GITHUB_WORKSPACE}/${tf_working_dir}/.terraform/plugins/linux_amd64/
          cd ${GITHUB_WORKSPACE}/${tf_working_dir}/.terraform/plugins/linux_amd64/
          curl -L https://github.com/banzaicloud/terraform-provider-k8s/releases/download/v${TERRAFORM_PROVIDER_K8S_VERSION}/terraform-provider-k8s_${TERRAFORM_PROVIDER_K8S_VERSION}_linux_amd64.tar.gz | tar xz terraform-provider-k8s
          mv terraform-provider-k8s terraform-provider-k8s_v${TERRAFORM_PROVIDER_K8S_VERSION}
        env:
          TERRAFORM_PROVIDER_K8S_VERSION: 0.7.6
```
