### ISSUE TITLE
fmt subcommand includes recursive flag even on older versions

### ISSUE THREAD

**Issue by FacetGraph** [hashicorp/terraform-github-actions#90]
I am trying to run fmt with terraform 0.11.7 but keep getting the usage method and the fmt command fails. I added the TF_LOG: 'trace' option to the env vars and found this.

```
2019/11/01 15:55:11 [INFO] CLI command args: []string{"fmt", "-check=true", "-list=true", "-check", "-write=false", "-list", "-recursive"}
flag provided but not defined: -recursive
Usage: terraform fmt [options] [DIR]

	Rewrites all Terraform configuration files to a canonical format.

	If DIR is not specified then the current working directory will be used.
	If DIR is "-" then content will be read from STDIN.

Options:

  -list=true       List files whose formatting differs (always false if using STDIN)

  -write=true      Write result to source file instead of STDOUT (always false if using STDIN or -check)

  -diff=false      Display diffs of formatting changes

  -check=false     Check if the input is formatted. Exit status will be 0 if all input is properly formatted and non-zero otherwise.
2019/11/01 15:55:11 [DEBUG] plugin: waiting for all plugin processes to complete...

##[error]Docker run failed with exit code 1
```

This is my code block

```
      - name: 'Terraform Format'                                            
        uses: hashicorp/terraform-github-actions@master                     
        with:                                                               
          tf_actions_version: 0.11.7                                        
          tf_actions_subcommand: 'fmt'                                      
          tf_actions_working_dir: 'infrastructure'                          
          tf_actions_comment: false                                         
        env:                                                                                                   
          TF_CLI_ARGS: '-check=true -list=true'                             
          TF_LOG: 'TRACE'
```
