### ISSUE TITLE
provide a way to run init with no backend

### ISSUE THREAD

**Issue by golonzovsky** [hashicorp/terraform-github-actions#95]
Would be quite useful to provide a way to run `terraform init -backend=false`.

This will make it possible to run `terrafrom validate` without providing sensitive GCP/AWS credentials to remote backends (see https://github.com/hashicorp/terraform/issues/15811#issuecomment-322511162).

Could be generic extension variable e.g: 
`initOutput=$(terraform init -input=false $INPUT_TF_ACTIONS_ARGS 2>&1)`

Or something more specific in case latter is too broad..

**Comment by sudomateo** [comment]
@golonzovsky Why don't you try to use the built-in [environment variables](https://www.terraform.io/docs/commands/environment-variables.html) like so?

```
name: 'Terraform Workflow'
on:
  - pull_request
jobs:
  example:
...
      - name: 'Terraform Init'
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_version: 0.12.13
          tf_actions_subcommand: 'init'
          tf_actions_comment: true
        env:
          TF_CLI_ARGS_init: '-backend=false'
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
 ...
```
