### ISSUE TITLE
Terraform Plan: define "out" parameter

### ISSUE THREAD

**Issue by alexbde** [hashicorp/terraform-github-actions#99]
From Terraform docs: 

> The optional -out argument can be used to save the generated plan to a file for later execution with terraform apply, which can be useful when running Terraform in automation.

Until terraform-github-actions/plan@v0.4.6 out parameter could be defined using `with` > `args` like that:

    - uses: hashicorp/terraform-github-actions/plan@v0.4.6
      with:
        args: -out example.tfplan

Is there a way setting output file name in v0.5.x?

**Comment by sudomateo** [comment]
You should be able to do this like so.

```
- name: 'Terraform Plan'
  uses: hashicorp/terraform-github-actions@master
  with:
    tf_actions_version: 0.12.13
    tf_actions_subcommand: 'plan'
    tf_actions_comment: true
  env:
    TF_CLI_ARGS_plan: '-out=example.tfplan'
    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```
